# Generated by Django 4.0.5 on 2022-06-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankemployee',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posterminal',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trader',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
